getresponse360_getresponse:
    resource: "@Getresponse360GetresponseBundle/Controller/"
    type:     annotation
    prefix:   /

getresponse360_replicator:
    resource: "@Getresponse360ReplicatorBundle/Controller/"
    type:     annotation
    prefix:   /

getresponse360_user:
    resource: "@Getresponse360UserBundle/Controller/"
    type:     annotation
    prefix:   /

getresponse360_api:
    resource: "@Getresponse360ApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
